//
//  MovieDetailFormatter.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 11.03.2021.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailFormatter {

}

// MARK: - Extensions -

extension MovieDetailFormatter: MovieDetailFormatterInterface {
    func getMovieDetailViewModel(response:MovieDetailModel) -> MovieDetailViewModel {
    
        return MovieDetailViewModel(title: response.title ?? "",
                                    posterUrl: response.posterPath ?? "",
                                    description: response.overview ?? "",
                                    voteCount: response.voteCount ?? 0,
                                    voteAvarage: response.voteAverage ?? 0)
    }
    
}
