//
//  MovieDetailWireframe.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 11.03.2021.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "MovieDetail", bundle: nil)

    // MARK: - Module setup -

    init(movieId:Int, title:String) {
        let moduleViewController = storyboard.instantiateViewController(ofType: MovieDetailViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = MovieDetailFormatter()
        let interactor = MovieDetailInteractor()
        let presenter = MovieDetailPresenter(view: moduleViewController,
                                             formatter: formatter,
                                             interactor: interactor,
                                             wireframe: self,
                                             movieId: movieId, title: title)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MovieDetailWireframe: MovieDetailWireframeInterface {
}
