//
//  MovieDetailInteractor.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 11.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

typealias GetMovieDetailCompletion = (_ model:MovieDetailModel?) -> ()

final class MovieDetailInteractor {
    let provider = ServiceProvider<MovieService>()
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
    func getMovieDetail(id: Int,completion: @escaping GetMovieDetailCompletion) {
        let movieId = String(id)
        provider.load(service: .movieDetail(id: movieId), decodeType: MovieDetailModel.self) { result in
            switch result {
                case .success(let response):
                    print("getMovieDetail success data received, response: \(response)")
                    completion(response)
                case .failure(let error):
                    print("getMovieDetail fail data received, error: \(error.localizedDescription)")
                    completion(nil)
                case .empty:
                    print("getMovieDetail No data")
                    completion(nil)
            }
        }
    }
    
}
