//
//  MovieListFormatter.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 9.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListFormatter {
}

// MARK: - Extensions -

extension MovieListFormatter: MovieListFormatterInterface {
}
