//
//  MovieListInterfaces.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 9.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
}

protocol MovieListViewInterface: ViewInterface {
    func updateMovieList()
}

protocol MovieListPresenterInterface: PresenterInterface {
    func fetchMoreMovie()
    func getTotalNumberOfMovies() -> Int
    func getCurrentNumberOfMovies() -> Int
    func getMovieCell(indexPath:IndexPath) -> MovieCellModel
}

protocol MovieListFormatterInterface: FormatterInterface {
    func appendMovieResponse(model:MoviesModel?)
    func getMovieCell(index:Int) -> MovieCellModel?
    func getTotalNumberOfMovies() -> Int
    func getCurrentNumberOfMovies() -> Int
    func calculateIndexPathsToReload(newResults: [MoviesModel.Result]) -> [IndexPath]
}

protocol MovieListInteractorInterface: InteractorInterface {
    func getMovies(pageNum:Int,completion: @escaping GetMoviesResult)
}
