//
//  MovieListInterfaces.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 9.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
}

protocol MovieListViewInterface: ViewInterface {
}

protocol MovieListPresenterInterface: PresenterInterface {
}

protocol MovieListFormatterInterface: FormatterInterface {
}

protocol MovieListInteractorInterface: InteractorInterface {
    func getMovies(pageNum:Int)
}
