//
//  MovieListInteractor.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 8.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
}
