//
//  MovieListInteractor.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 9.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
    let provider = ServiceProvider<MovieService>()
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
    func getMovies(pageNum: Int) {
     
        provider.load(service: .popularMovies(page: "1"), decodeType: MoviesModel.self) { result in
            print("res \(result)")
            switch result {
                case .success(let resp):
                    print(resp)
                case .failure(let error):
                    print(error.localizedDescription)
                case .empty:
                    print("No data")
            }
        }
    
    }
    
}
