//
//  MovieListWireframe.swift
//  Movie
//
//  Created by Mehmet Emin Deniz on 9.03.2021.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Main", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: MovieListViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = MovieListFormatter()
        let interactor = MovieListInteractor()
        let presenter = MovieListPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MovieListWireframe: MovieListWireframeInterface {
}
